"""Sample datasets for the notebooks.

Real business data from games, SaaS and tech companies is almost never
public, so most notebooks here use data generated by this file. That has one
big advantage for learning: we know the truth. Each generator plants a few
real effects (one channel churns faster, one feature lifts conversion), and
the notebooks check whether the analysis finds them.

Everything is seeded, so the numbers are the same on every run. None of it
describes a real company, player or patient.

The medicine diagnosis notebook uses a real dataset that ships with
scikit-learn, and the statistics notebook uses a real published study.
"""

import numpy as np
import pandas as pd


# --------------------------------------------------------------------- SaaS
def saas_subscriptions(seed: int = 7):
    """Thirty months of a B2B subscription business.

    Returns (customers, monthly_revenue).

    Planted effects:
      - Paid search customers churn about twice as fast as organic ones.
      - Churn is highest in the first three months, then settles.
      - About 2% of active customers upgrade one plan each month.
      - New sign-ups grow roughly 4% a month.
    """
    rng = np.random.default_rng(seed)
    months = pd.period_range("2023-01", periods=30, freq="M")
    plans = {"Basic": 29, "Pro": 99, "Enterprise": 499}
    plan_names = list(plans)
    channel_cac = {"Organic": 150, "Paid search": 650, "Partner": 400}
    channel_mix = [0.45, 0.35, 0.20]
    channel_churn_mult = {"Organic": 1.0, "Paid search": 2.0, "Partner": 0.8}
    plan_churn = {"Basic": 0.045, "Pro": 0.025, "Enterprise": 0.012}

    customers, revenue = [], []
    cid = 0
    for m_idx, month in enumerate(months):
        n_new = int(rng.poisson(80 * 1.04 ** m_idx))
        for _ in range(n_new):
            cid += 1
            channel = rng.choice(list(channel_cac), p=channel_mix)
            plan = rng.choice(plan_names, p=[0.6, 0.32, 0.08])
            cac = channel_cac[channel] * rng.uniform(0.7, 1.3) * (1 + plan_names.index(plan))
            churn_month = None
            for t, active_month in enumerate(months[m_idx:]):
                revenue.append((cid, active_month, plan, plans[plan]))
                early_boost = 2.5 if t < 3 else 1.0
                p_churn = plan_churn[plan] * channel_churn_mult[channel] * early_boost
                if rng.random() < p_churn:
                    churn_month = active_month
                    break
                if plan != "Enterprise" and rng.random() < 0.02:
                    plan = plan_names[plan_names.index(plan) + 1]
            customers.append({
                "customer_id": cid, "signup_month": month, "channel": channel,
                "acquisition_cost": round(cac, 2), "churn_month": churn_month,
            })
    revenue = pd.DataFrame(revenue, columns=["customer_id", "month", "plan", "mrr"])
    customers = pd.DataFrame(customers)
    first_plan = revenue.groupby("customer_id")["plan"].first()
    customers["starting_plan"] = customers["customer_id"].map(first_plan)
    return customers, revenue


def saas_churn_snapshot(n: int = 6000, seed: int = 11) -> pd.DataFrame:
    """One row per account, taken on a snapshot date, with whether the
    account cancelled in the following 90 days.

    Planted effects (in order of strength):
      - Days since last login and low feature adoption drive churn most.
      - Support tickets help up to a point, then signal frustration.
      - Seats (account size) protects against churn.
      - `refund_issued` is LEAKAGE: refunds happen after cancelling, so it
        "predicts" churn perfectly and would be useless in real life.
    """
    rng = np.random.default_rng(seed)
    plan = rng.choice(["Basic", "Pro", "Enterprise"], n, p=[0.55, 0.35, 0.10])
    seats = np.where(plan == "Enterprise", rng.integers(20, 200, n),
                     np.where(plan == "Pro", rng.integers(3, 30, n), rng.integers(1, 5, n)))
    tenure = rng.gamma(2.0, 8.0, n).round().astype(int) + 1
    adoption = np.clip(rng.beta(2, 2, n) + 0.002 * tenure, 0, 1)
    days_since_login = np.round(rng.exponential(6, n) / (0.3 + adoption)).astype(int)
    logins = np.clip(rng.poisson(30 * adoption + 2), 0, None)
    tickets = rng.poisson(2.5, n)
    nps = np.clip(np.round(rng.normal(6 + 3 * adoption, 2)), 0, 10).astype(int)

    logit = (-0.5 + 0.09 * days_since_login - 2.8 * adoption - 0.012 * seats
             - 0.6 * np.minimum(tickets, 2) + 1.0 * np.maximum(tickets - 3, 0)
             - 0.12 * (nps - 6) - 0.015 * tenure)
    churned = rng.random(n) < 1 / (1 + np.exp(-logit))
    refund = churned & (rng.random(n) < 0.7)

    return pd.DataFrame({
        "account_id": np.arange(1, n + 1), "plan": plan, "seats": seats, "tenure_months": tenure,
        "feature_adoption": adoption.round(3), "logins_last_30d": logins,
        "days_since_last_login": days_since_login, "support_tickets_90d": tickets, "nps": nps,
        "refund_issued": refund.astype(int), "churned_next_90d": churned.astype(int),
    })


# -------------------------------------------------------------------- Games
def game_players(n: int = 20000, seed: int = 3):
    """A mobile game's first 120 days after launch.

    Returns (players, sessions, purchases).

    Planted effects:
      - Players who finish the tutorial retain far better.
      - Retention decays fast in the first week, then slowly.
      - iOS players are about 1.6x as likely to pay.
      - A weekend bump in daily activity.
    """
    rng = np.random.default_rng(seed)
    launch = pd.Timestamp("2024-03-01")
    days = 120
    install_day = np.sort(rng.integers(0, days - 7, n))
    platform = rng.choice(["iOS", "Android"], n, p=[0.42, 0.58])
    source = rng.choice(["Organic", "Paid UA", "Cross-promo"], n, p=[0.5, 0.35, 0.15])
    country = rng.choice(["US", "BR", "DE", "JP", "IN"], n, p=[0.3, 0.2, 0.15, 0.15, 0.2])
    tutorial = rng.random(n) < np.where(source == "Paid UA", 0.62, 0.78)
    engagement = rng.lognormal(0, 0.6, n) * np.where(tutorial, 1.0, 0.35)

    session_rows, purchase_rows = [], []
    max_level = np.zeros(n, dtype=int)
    for i in range(n):
        lifetime = 1 + int(rng.exponential(10 * engagement[i]))
        last = min(install_day[i] + lifetime, days)
        level = 0
        for d in range(install_day[i], last):
            weekday = (launch + pd.Timedelta(days=d)).dayofweek
            p_play = 0.95 if d == install_day[i] else min(0.9, 0.45 * engagement[i] + (0.1 if weekday >= 5 else 0))
            if rng.random() < p_play:
                minutes = rng.gamma(2, 6 * engagement[i] ** 0.5)
                level += int(minutes // 12) + (1 if rng.random() < 0.3 else 0)
                session_rows.append((i + 1, d, round(minutes, 1)))
                pay_p = 0.005 * (1.6 if platform[i] == "iOS" else 1.0) * min(engagement[i], 3)
                if rng.random() < pay_p:
                    purchase_rows.append((i + 1, d, rng.choice([0.99, 4.99, 9.99, 19.99, 49.99, 99.99],
                                                                p=[0.35, 0.3, 0.17, 0.1, 0.06, 0.02])))
        max_level[i] = level

    players = pd.DataFrame({
        "player_id": np.arange(1, n + 1), "install_date": launch + pd.to_timedelta(install_day, "D"),
        "platform": platform, "source": source, "country": country,
        "finished_tutorial": tutorial, "max_level": max_level,
    })
    sessions = pd.DataFrame(session_rows, columns=["player_id", "day", "minutes"])
    sessions["date"] = launch + pd.to_timedelta(sessions.pop("day"), "D")
    purchases = pd.DataFrame(purchase_rows, columns=["player_id", "day", "amount_usd"])
    purchases["date"] = launch + pd.to_timedelta(purchases.pop("day"), "D")
    return players, sessions, purchases


def game_ab_test(n: int = 60000, seed: int = 21) -> pd.DataFrame:
    """A 14-day test of a new starter-pack offer, one row per player.

    Planted effects:
      - The variant really lifts conversion: 3.0% -> 3.45% (a 15% relative lift).
      - Spend per payer is heavy-tailed (a few "whales"), and is the same in
        both groups, so revenue per player rises only through conversion.
    """
    rng = np.random.default_rng(seed)
    group = rng.choice(["control", "variant"], n)
    day = rng.integers(1, 15, n)
    p = np.where(group == "variant", 0.0345, 0.030)
    converted = rng.random(n) < p
    spend = np.where(converted, np.round(rng.lognormal(2.0, 1.1, n), 2), 0.0)
    return pd.DataFrame({"player_id": np.arange(1, n + 1), "group": group, "day_enrolled": day,
                         "converted": converted.astype(int), "spend_usd": spend})


def game_player_behaviour(n: int = 4000, seed: int = 5):
    """Thirty days of behaviour per player, for segmentation.

    Returns (features, hidden_persona). The personas are what generated the
    data; a clustering notebook should rediscover them without being told.
      casual 50%, grinder 25%, social 18%, whale 7%
    """
    rng = np.random.default_rng(seed)
    personas = rng.choice(["casual", "grinder", "social", "whale"], n, p=[0.5, 0.25, 0.18, 0.07])
    spec = {  # sessions/week, minutes/session, spend 30d, pvp share, friends
        "casual": (3, 8, 0.5, 0.10, 2),
        "grinder": (12, 35, 3, 0.30, 4),
        "social": (8, 18, 2, 0.15, 25),
        "whale": (10, 30, 180, 0.55, 8),
    }
    rows = []
    for p in personas:
        s, m, spend, pvp, fr = spec[p]
        rows.append({
            "sessions_per_week": max(0.5, rng.normal(s, s * 0.45)),
            "avg_session_minutes": max(1, rng.normal(m, m * 0.45)),
            "spend_30d_usd": max(0, rng.lognormal(np.log(spend + 0.01), 1.0)),
            "pvp_share": float(np.clip(rng.normal(pvp, 0.14), 0, 1)),
            "friends": max(0, int(rng.normal(fr, fr * 0.55 + 1))),
        })
    return pd.DataFrame(rows).round(2), pd.Series(personas, name="persona")


# ----------------------------------------------------------------- Medicine
def clinical_trial(n: int = 800, seed: int = 13) -> pd.DataFrame:
    """A two-arm trial with time-to-event outcomes (months to disease progression).

    Planted effects:
      - The treatment cuts the hazard by 30% (true hazard ratio 0.70).
      - Each extra 10 years of age raises the hazard by about 35%.
      - Patients are followed for at most 36 months; some drop out early.
        Those patients are "censored": we know they hadn't progressed yet,
        not that they never would.
    """
    rng = np.random.default_rng(seed)
    treatment = rng.integers(0, 2, n)
    age = np.clip(rng.normal(62, 10, n), 30, 90).round()
    stage = rng.choice([2, 3], n, p=[0.6, 0.4])
    hazard = 0.035 * np.exp(np.log(0.70) * treatment + 0.03 * (age - 62) + 0.5 * (stage == 3))
    event_time = rng.exponential(1 / hazard)
    dropout = rng.exponential(120, n)
    follow_up = np.minimum(36, dropout)
    observed = event_time <= follow_up
    return pd.DataFrame({
        "patient_id": np.arange(1, n + 1), "arm": np.where(treatment == 1, "treatment", "control"),
        "age": age.astype(int), "stage": stage,
        "months": np.round(np.minimum(event_time, follow_up), 2), "progressed": observed.astype(int),
    })


# --------------------------------------------------------------------- Tech
def web_traffic(seed: int = 17) -> pd.Series:
    """Daily visits to a product website over three years.

    Planted effects: steady growth, a strong weekday/weekend pattern, a
    yearly cycle (quiet in late December), a product launch on 2024-09-10
    that permanently lifts traffic ~25%, and a 3-day outage with missing data.
    """
    rng = np.random.default_rng(seed)
    dates = pd.date_range("2022-07-01", "2025-06-30", freq="D")
    t = np.arange(len(dates))
    trend = 20000 * (1 + 0.0006) ** t
    weekly = np.array([1.08, 1.12, 1.10, 1.06, 0.98, 0.78, 0.74])[dates.dayofweek]
    yearly = 1 + 0.10 * np.cos(2 * np.pi * (dates.dayofyear - 80) / 365.25)
    holiday = np.where((dates.month == 12) & (dates.day >= 22), 0.65, 1.0)
    launch = np.where(dates >= "2024-09-10", 1.25, 1.0)
    visits = trend * weekly * yearly * holiday * launch * rng.lognormal(0, 0.05, len(dates))
    series = pd.Series(visits.round(), index=dates, name="visits")
    series.loc["2023-04-11":"2023-04-13"] = np.nan
    return series


def server_metrics(seed: int = 23):
    """Two weeks of per-minute API latency for one service.

    Returns (metrics, true_anomaly) where true_anomaly marks the incidents we
    planted: short slowdowns, one slow memory-leak style drift, and a step up
    after a bad deploy. There are also harmless one-minute blips (like
    garbage-collection pauses) that are NOT incidents: nobody should be
    paged for them, and they're the classic source of false alarms.
    """
    rng = np.random.default_rng(seed)
    idx = pd.date_range("2025-03-01", periods=14 * 24 * 60, freq="min")
    minute_of_day = np.asarray(idx.hour * 60 + idx.minute)
    daily = 1 + 0.6 * np.clip(np.sin(2 * np.pi * (minute_of_day - 7 * 60) / 1440), 0, None)
    latency = 110 * daily * rng.lognormal(0, 0.10, len(idx))
    anomaly = np.zeros(len(idx), dtype=bool)

    blips = rng.choice(len(idx), 14 * 8, replace=False)
    latency[blips] *= rng.uniform(1.8, 3.0, len(blips))

    for start in rng.choice(np.arange(4 * 1440, len(idx) - 500), 10, replace=False):
        width = rng.integers(6, 25)
        latency[start:start + width] *= rng.uniform(1.6, 2.6)
        anomaly[start:start + width] = True

    drift_start, drift_end = 6 * 1440 + 2 * 60, 6 * 1440 + 12 * 60
    latency[drift_start:drift_end] *= np.linspace(1, 1.8, drift_end - drift_start)
    anomaly[drift_start + 150:drift_end] = True

    shift_start = 10 * 1440 + 13 * 60
    latency[shift_start:shift_start + 240] *= 1.45
    anomaly[shift_start:shift_start + 240] = True

    metrics = pd.DataFrame({"latency_ms": latency.round(1)}, index=idx)
    return metrics, pd.Series(anomaly, index=idx, name="true_anomaly")
